version: '3.2'

services:
    db:
        image: postgres:11
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - helix-db-data:/var/lib/postgresql/data
    server:
        build:
          context: .
        command: sh -c 'python manage.py migrate && python manage.py init_roles && python manage.py runserver 0.0.0.0:9000'
        env_file:
            - .env
        environment:
            - DJANGO_SETTINGS_MODULE=helix.settings
            - DEBUG=True
        volumes:
            - .:/code
        ports:
            - '9000:9000'
        depends_on:
            - db

volumes:
  helix-db-data:
